### ISSUE TITLE
Some CSS is not rendering after clicking on preloaded link from Next.js

### ISSUE THREAD

**Issue by srflp** [dives-app/dives-frontend#2]
It seems like our app is suffering from this pretty fresh bug in Next.js:
https://github.com/vercel/next.js/issues/16932

Every time when CSS doesn't load correctly JS prints this warning:
![image](https://user-images.githubusercontent.com/17103865/95142054-18954000-0773-11eb-8b20-17a5aff71d90.png)

**Comment by HarshBoricha404** [comment]
This issue still persisted for me using nextjs.
what I did was to make this work was to add this script inside _document.tsx (global parent for all the pages)
```javascript
     <script
            dangerouslySetInnerHTML={{
              __html: `
              if(document) {
            document.querySelectorAll("link[rel='preload'][as='style']").forEach(link => link.rel = "stylesheet")}
            `
            }}
          />
```
